---
title: "hw6"
author: "Yu Zhou"
date: "March 29, 2015"
output: html_document
---

```{r}
setwd("~/src/edxRlabs/course3")
```

```{r}
p <- 0.49
dbinom(2, 4, p)
dbinom(4, 10, p)
```

```{r}
pgc <- 0.4
1-pbinom(10, 20, 0.4)
```

```{r}
1-pbinom(0, 189000000, 1/175223510)
1-pbinom(1, 189000000, 1/175223510)
```

```{r}
N <- 20
p <- 0.4
pbinom(20*0.45, 20, 0.4) - pbinom(20*0.35, 20, 0.4)
m <- N*p
s <- sqrt(N*p*(1-p))
pnorm(20*0.45, m, s) - pnorm(20*0.35, m, s)

b <- (9 - 20*.4)/sqrt(20*.4*.6)
a <- (7 - 20*.4)/sqrt(20*.4*.6)
pnorm(b)-pnorm(a)
```

```{r}
N <- 1000
p <- 0.4
pb <- pbinom(N*0.45, N, p) - pbinom(N*0.35, N, p)
pn <- pnorm((N*0.45 - N*p)/sqrt(N*p*(1-p))) - pnorm((N*0.35 - N*p)/sqrt(N*p*(1-p)))
pb - pn
```


### QUESTION 4.1.5    
```{r}
Ns <- c(5,10,30,100)
ps <- c(0.01,0.10,0.5,0.9,0.99)
params <- expand.grid(N=Ns, p=ps)
library(rafalib)
mypar2(5, 4)
apply(params, 1, function(x) {
  N <- x[1]
  p <- x[2]
  k <- 1:(N-1)
  a <- (k+0.5 - N*p)/sqrt(N*p*(1-p))
  b <- (k-0.5 - N*p)/sqrt(N*p*(1-p))
  approx <- pnorm(a) - pnorm(b)
  exact <- dbinom(k,N,p)
  LIM <- range(c(approx, exact)) # good tip
  plot(exact, approx, main=sprintf("%d, %.2f", N, p), xlim=LIM, ylim=LIM, col=1, pch=16)
  abline(a=0, b=1)
})
```

### QUESTION 4.1.6
```{r}
N <- 189000000
p <- 1/175223510
exact <- dbinom(2, N, p)

a <- (2+0.5 - N*p)/sqrt(N*p*(1-p))
b <- (2-0.5 - N*p)/sqrt(N*p*(1-p))
pn <- pnorm(a) - pnorm(b)

pp <- dpois(2,N*p)
c(exact, pn, pp)

1 - ppois(1, N*p)
```


### QUESTION 4.2.1
```{r, eval=FALSE}
library(devtools)
install_github("genomicsclass/dagdata")
```

```{r}
library(dagdata)
data(hcmv)
library(rafalib)
mypar2()
plot(locations,rep(1,length(locations)),ylab="",yaxt="n")

breaks=seq(0,4000*round(max(locations)/4000),4000)
tmp=cut(locations,breaks)
counts=as.numeric(table(tmp))
counts
hist(counts)

probs <- dpois(counts,4)
likelihood <- prod(probs)
likelihood

logprobs <- dpois(counts,4,log=TRUE)
loglikelihood <- sum(logprobs)
loglikelihood

llpois <- function(counts, lambda) {
  logprobs <- dpois(counts, lambda, log=TRUE)
  sum(logprobs)
}

lambdas <- seq(0, 15, len=300)
ll <- sapply(lambdas, function(x) llpois(counts, x))
plot(lambdas, ll)
mle <- lambdas[which.max(ll)]
mle
abline(v=lambdas[which.max(ll)])

mean(counts)
```

```{r}
binLocation <- (breaks[-1]+breaks[-length(breaks)])/2  # good tip
plot(binLocation,counts,type="l",xlab=)
binLocation[which.max(counts)]
max(counts)
```

```{r}
lambda = mean(counts[ - which.max(counts) ])
lambda
1 - ppois(13, lambda)
```

```{r}
0.05 / length(counts)
```


```{r}
ps <- (seq(along=counts) - 0.5)/length(counts)
lambda <- mean( counts[ -which.max(counts)])
poisq <- qpois(ps,lambda)
qqplot(poisq,counts)
abline(0,1)
```

### QUESTION 4.3.1  
```{r, eval=FALSE}
library(devtools)
install_github("genomicsclass/tissuesGeneExpression")
```

```{r}
library(tissuesGeneExpression)
data("tissuesGeneExpression")
library(genefilter)
y = e[, which(tissue=="endometrium")]
dim(y)
```

```{r}
#sv <- apply(y, 1, var)
sv <- rowVars(y)
mypar2(1, 2)
qqnorm(sv)
qqline(sv)

qqnorm(sqrt(sv))
qqline(sqrt(sv))

```

```{r}
library(limma)
sdf <- fitFDist(sv, ncol(y)-1)
sdf
sv1 <- qf((seq(along=sv)-0.5)/length(sv), 14, sdf$df2)*sdf$scale
qqplot(sqrt(sv), sv1)
abline(0, 1)

qqplot(sqrt(sv), rf(length(sv), 14, sdf$df2)*sdf$scale)
abline(0, 1)

```

```{r}
s2 <- rowVars(y)
library(limma)
estimates=fitFDist(s2,14)
print( estimates$scale )
ps <- (seq(along=s2)-0.5)/length(s2)
theoretical<- qf(ps, 14, estimates$df2)*estimates$scale  ### 
LIM <- sqrt( range(c(theoretical,s2)) )
mypar(1,2)
qqplot(sqrt( theoretical ), sqrt( s2 ),ylim=LIM,xlim=LIM)
abline(0,1)
##close up excluding the upper 5%
K <- sqrt( quantile(s2,0.95) )
qqplot( sqrt( theoretical ), sqrt( s2 ),ylim=c(0,K),xlim=c(0,K))
abline(0,1)
```

